language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - gem --version

script: 
  - CXX 4374_Task1c_Skeleton.cpp -o project.o;

after_success:
  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi

notifications:
  email: false

env:
