language: cpp

compiler:
  - gcc
  - emscripten
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - gem --version

script: 
  - gcc 4374_Task1c_emscripten.cpp -I RandomUtils.h TimeUtils.h -o project.o;
  - emcc 4374_Task1c_emscripten.cpp -I RandomUtils.h TimeUtils.h -o project.o;
  - clang 4374_Task1c_emscripten.cpp -I RandomUtils.h TimeUtils.h -o project.o;

after_success:
  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi

notifications:
  email: false

env:
