language: cpp

compiler:
  - gcc
  - emscripten
  - clang

script: 
  - CXX 4374_Task1c_emscripten.cpp -o project.o;

after_success:
  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi

notifications:
  email: false

env:
