language: cpp
sudo: required

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -y libsdl1.2debian libsdl1.2-dev libsdl-image1.2 libsdl-image1.2-dev libsdl-ttf2.0-0 libsdl-ttf2.0-dev

script: 
  - g++ 4374_Task1c_linux.cpp -o project.o;
  - clang++ 4374_Task1c_linux.cpp -o project.o;

after_success:
  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi

notifications:
  email: false
