language: cpp

compiler:
  - gcc
  - clang

script: 
  - gcc 4374_Task1c_linux.cpp -o project.o;
  - clang 4374_Task1c_linux.cpp -o project.o;

after_success:
  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi

notifications:
  email: false

env:
